# kubernetes-yaml/03_frontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: fintech-app
    tier: frontend
spec:
  replicas: 2 # Escalamiento: 2 copias para resiliencia
  selector:
    matchLabels:
      app: fintech-app
      tier: frontend
  template:
    metadata:
      labels:
        app: fintech-app
        tier: frontend
    spec:
      containers:
      - name: frontend-container
        # **Â¡IMPORTANTE!** Reemplaza 'tu-usuario' por tu usuario real de Docker Hub/ECR
        image: jfcpjimmy/fintech-frontend:1.0 
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"